# conda environment description file for readthedocs build environment

name: {{ cookiecutter.conda_dev_env_name }}-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python={{ cookiecutter.dev_python_version }}

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
