# conda environment description file for {{ cookiecutter.package_name }} package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f {{ cookiecutter.package_name }}/envs/environment-dev.yaml
#   $ conda activate {{ cookiecutter.conda_dev_env_name }}
#   ({{ cookiecutter.conda_dev_env_name }})$ python3 -m pip install --editable {{ cookiecutter.package_name }}
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in recent development.

name: {{ cookiecutter.conda_dev_env_name }}

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python={{ cookiecutter.dev_python_version }}

  # For coding style, repo QA, and pkg management
  - black
  - hatch
  - pre-commit

  # For unit tests
  - coverage
  - pytest-cov
  - tomli

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    # For unit tests
    - pytest-randomly
