# conda environment description file for {{ cookiecutter.package_name }} package
# testing environment
#
# Creates a conda environment in which the {{ cookiecutter.package_name }} package
# unit tests and coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: {{ cookiecutter.conda_dev_env_name }}-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python={{ cookiecutter.dev_python_version }}

  # For unit tests and coverage monitoring
  - coverage
  - pytest-cov
  - tomli

  # For documentation links checking
  - sphinx
  - sphinx_rtd_theme

  - pip:
    # For unit tests
    - pytest-randomly
