# conda environment description file for readthedocs build environment

name: {{ cookiecutter.conda_dev_env_name }}-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python={{ cookiecutter.dev_python_version }}

  # Sphinx and extensions
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    # Install the {{ cookiecutter.package_name }} package in editable mode
    - --editable ../
