# conda environment description file for {{ cookiecutter.package_name }} package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f {{ cookiecutter.package_name }}/env/environment-dev.yaml
#   $ source activate {{ cookiecutter.package_name.lower() }}
#   ({{ cookiecutter.package_name.lower() }})$ pip install --editable {{ cookiecutter.package_name }}
#
# The environment will also include all of the tools used to develop,
# test, and document the {{ cookiecutter.package_name }} package.
#
# See the env/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: {{ cookiecutter.package_name.lower() }}

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python={{ cookiecutter.dev_python_version }}

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
