# conda environment description file for the cookiecutter environment that is
# required to create packages using the cookiecutter-moad-pypkg cookie cutter
#
# Create a conda environment in which to run cookiecutter with:
#
#   $ conda env create -f cookiecutter-moad-pypkg/envs/environment.yaml
#   $ conda activate cookiecutter
#
# See the envs/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: cookiecutter

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cookiecutter
  - pip
  - python=3.9
