[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
source = [ "{{ cookiecutter.package_slug }}", "tests"]

[tool.coverage.report]
show_missing = true
